project_id = "hgfulxwjwjohmjslhxhq"

[functions.delete-user]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.send-application-email]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-fee-receipt]
verify_jwt = false

[functions.admin-otp]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-fee-reminder]
verify_jwt = false

[functions.passkey-authenticate]
verify_jwt = false

[functions.passkey-register]
verify_jwt = false

[functions.send-promotion-notification]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.create-staff]
verify_jwt = false

[functions.send-fcm-notification]
verify_jwt = false

[functions.student-chat]
verify_jwt = false
