project_id = "hgfulxwjwjohmjslhxhq"

[functions.delete-user]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.send-application-email]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-fee-receipt]
verify_jwt = false

[functions.admin-otp]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
