
ALTER TABLE public.students
ADD COLUMN IF NOT EXISTS aadhaar_number TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS nationality TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS religion TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS caste TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS blood_group TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT '';
